//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CASCBruteforcer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CASCBruteforcer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Defines
        ///#define HASHES_SIZE {HASHES_SIZE}
        ///#define BUCKET_SIZE {BUCKET_SIZE} // max length of hashes grouped by first byte
        ///#define DATA_SIZE {DATA_SIZE}
        ///#define DATA_SIZE_MINUS (DATA_SIZE - 12)
        ///#define HASH_PRIME (0xdeadbeef + {DATA_SIZE_REAL})
        ///#define OFFSETS_SIZE {OFFSETS_SIZE}
        ///#define NEXT_CHAR (1.0 / 39.0) // (1 / Charset.Length)
        ///
        ///// Constants
        ///constant uint Offsets[OFFSETS_SIZE] = { {OFFSETS} };
        ///constant char Charset[39] = &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_- &quot;;
        ///constant ulong HashLooku [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Jenkins {
            get {
                return ResourceManager.GetString("Jenkins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///// Placeholders:
        /////   DATA = data to decrypt (4 bytes)
        /////   MAGIC = magic to bruteforce (4 bytes)
        /////   IV0 = first 4 bytes of the IV
        /////   IV1 = second 4 bytes of the IV
        ///
        ///constant uchar Data[{DATA_SIZE}] = { {DATA} };
        ///constant uchar Magic[{MAGIC_SIZE}] = { {MAGIC} };
        ///
        ///uint rotl(uint bits, uint amount) {
        ///	return (bits &lt;&lt; amount) | (bits &gt;&gt; (32 - amount));
        ///}
        ///
        ///void salsa20(uint *dancers) {
        ///	
        ///	uint x[16];
        ///
        ///	#ifdef opencl_unroll_hint
        ///	__attribute__((opencl_unroll_hint))
        ///	#endif
        ///	for(uint i = [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Salsa {
            get {
                return ResourceManager.GetString("Salsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Defines
        ///#define HASHES_SIZE {HASHES_SIZE}
        ///#define BUCKET_SIZE {BUCKET_SIZE} // max length of hashes grouped by first byte
        ///#define DATA_SIZE {DATA_SIZE_REAL}
        ///#define OFFSETS_SIZE {OFFSETS_SIZE}
        ///#define NEXT_CHAR (1.0 / 26.0) // (1 / Charset.Length)
        ///
        ///// Constants
        ///constant uint Offsets[OFFSETS_SIZE] = { {OFFSETS} };
        ///constant char Charset[26] = &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;;
        ///constant uint HashLookup[HASHES_SIZE] = { {HASHES} }; // hashes to find, sorted by first byte
        ///constant ushort HashOffsets[256 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
    }
}
